services:
  - type: web
    name: rubinot-death-tracker
    env: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
